---
title: "Plotly examples"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Examples of plotly

We're gonna look at NYX Airbnb data.

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```


```{r}
data("nyc_airbnb")

nyc_airbnb_df = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location/2) %>% 
  select(neighbourhood_group,neighbourhood,rating, price, room_type, lat, long) %>% 
  filter(
    neighbourhood_group == "Manhattan",
    price %in% 100:500,
    room_type == "Entire home/apt"
  ) %>% 
  drop_na(rating)
```

# Plotly plots

## scatterplot

```{r}
nyc_airbnb_df %>% 
  mutate(text_label = str_c("Price : $", price, "\nRating:",rating)) %>% 
  plot_ly(
    x=~lat, y = ~long, color = ~price, alpha =.5, text = ~text_label,
          type = "scatter", mode = "markers")
```

## boxplot

```{r}
nyc_airbnb_df %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood,price)) %>% 
  plot_ly(y=~price, x=~neighbourhood, color = ~neighbourhood,
          type = "violin", colors = "viridis")
```

## bar plot

```{r}
nyc_airbnb_df %>%
  count(neighbourhood) %>% 
  mutate(neighbourhood= fct_reorder(neighbourhood,n)) %>% 
  plot_ly(x= ~neighbourhood, y = ~n, color = ~neighbourhood,
          type = "bar", colors = "viridis")
```

# ggplotly

```{r}
ggp_scatter=
nyc_airbnb_df %>% 
  ggplot(aes(x=lat,y=long, color=price))+
  geom_point()

ggplotly(ggp_scatter)
```

